### ISSUE TITLE
Car Dupe I guess???

### ISSUE THREAD

**Issue by Pluto-Really** [MaDHouSe79/mh-parking#25]
![Capture](https://user-images.githubusercontent.com/92813476/160254596-d90f7df6-ced7-429a-a8b2-fbecfa0ab861.PNG)

**Comment by gfrast** [comment]
same problem here

**Comment by MaDHouSe79** [comment]
there is a timedeley in the config? fif you ue that? try to set it on 1500 and 500 for freezedeley

**Comment by darthmoebius** [comment]
I'm having the same problem. Each client spawns a car. There is a delay between car A and car B, but if 10 players are on the server, car A spawns 10 times, then 1500ms later car B spawns 10 times.
![Screenshot_62](https://user-images.githubusercontent.com/85351662/163287699-826465dc-c3e0-4ff9-82a8-d86707f9b355.png)

**Comment by MaDHouSe79** [comment]
Use the parking lite version, that version works for now,
i have to fix the normal version but it have some delay
