### ISSUE TITLE
Entering apartment messes up script.  

### ISSUE THREAD

**Issue by Kalizar86** [MaDHouSe79/mh-parking#26]
If I park the car outside of the default apartment in qb-core and then go inside and come back out it tries to park the car instead of unpark the car even though the car is stuck in place and can't be moved until it's unparked.  

https://streamable.com/qaxgt0

**Comment by Kalizar86** [comment]
Oh I will say that relogging will fix it but it still seems weird.

**Comment by MaDHouSe79** [comment]
Ok, uhm it look like the houseing if doing something i dont know, i will check it and see if i can fix it.
