### ISSUE TITLE
Marker is not Showing when create Parking by /park-cmenu

### ISSUE THREAD

**Issue by nutter887** [MaDHouSe79/mh-parking#32]
Hi i got some problem when i use /park-cmenu marker not showing up.
i try to add vip but ti's not work.

**Comment by MaDHouSe79** [comment]
Hi you also need to enable the bmode (build mode) then use the cmode (create mode)

**Comment by nutter887** [comment]
> Hi you also need to enable the bmode (build mode) then use the cmode (create mode)

Thanks for helping, I enable all yet and yes it's have marker but just on font my vehicle, but it's still not showing like park
name,or maker on the floor. Or i missing something?

[](https://www.img.in.th/image/d7hkwQ)

[](https://www.img.in.th/image/d7h2ng)

**Comment by MaDHouSe79** [comment]
The markers on front of your vehicele is only just a easy way to line up with other markers, but it has to be enable by command, not in the config file, don't thouch that in the config or it wil not work anymore. just read it cause i put text afer ever value that it does. please read :)

**Comment by nutter887** [comment]
thank you!
