### ISSUE TITLE
Quick idea

### ISSUE THREAD

**Issue by tsoulii** [MaDHouSe79/mh-parking#39]
Why not make mh-parking save the last parking location of the car without having to press F5? 
The idea was copied from MojiaGarages

**Comment by MaDHouSe79** [comment]
Make from F5 -> F  this is the button when you get out the vehicle. (see config.lua)

**Comment by MaDHouSe79** [comment]
The example you use is, if the server or you suddenly drops or leaves the server without you pressing anything, if I have to do this then I have to check your coords every 1 mil secs to check where you are and save it every time, This takes more process, if this has to be done for every player then I don't know if it will still remain stable?

**Comment by tsoulii** [comment]
I understand, stability is important
  It was just a suggestion. If it will cause problems, then there is no need to do that
  Thank you for your efforts
  Have you deleted your Discord server?

**Comment by MaDHouSe79** [comment]
Yes I deleted it, it was barely used.
