### ISSUE TITLE
[Question/Help] SQL Errors the day after it working fine

### ISSUE THREAD

**Issue by Cynist3r** [MaDHouSe79/mh-parking#42]
[Question/Help]

After using this in my test server perfectly, Multiple restarts with no errors and was working awesome, I moved it into my live server. I made sure to enter my SQL and I am now getting the errors below today.

I then went into my test server to see if there had been a change there and yes, It also was not working? I had not touched anything as once I got this working I called it a night. So I am very confused on what to do or what has happened

(node:137) UnhandledPromiseRejectionWarning: Error: mh-parking was unable to execute a query!
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `player_parking_vips` (
            `id` int(10) N...' at line 22
        CREATE TABLE IF NOT EXISTS `player_parking` (
            `id` int(10) NOT NULL AUTO_INCREMENT,
            `citizenid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `citizenname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `model` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `modelname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `plate` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `steerangle` int(15) NOT NULL DEFAULT 0,
            `fuel` int(15) NOT NULL DEFAULT 0,
            `engine` int(15) NOT NULL DEFAULT 0,
            `body` int(15) NOT NULL DEFAULT 0,
            `oil` int(15) NOT NULL DEFAULT 0,
            `data` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `coords` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            `time` bigint(20) NOT NULL,
            `cost` int(10) NOT NULL DEFAULT 0,
            `parktime` int(10) NOT NULL DEFAULT 0,
            `parking` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
            PRIMARY KEY (`id`) USING BTREE
        ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
        
        CREATE TABLE IF NOT EXISTS `player_parking_vips` (
            `id` int(10) NOT NULL AUTO_INCREMENT,
            `citizenid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `citizenname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `maxparking` int(10) NOT NULL DEFAULT 0,
            `hasparked` int(10) NOT NULL DEFAULT 0,
            PRIMARY KEY (`id`) USING BTREE
        ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
         []
    at @oxmysql/dist/build.js:22275:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)

I have not ran into any errors like this before so I am just looking for some suggestions or help.

**Comment by Cynist3r** [comment]
And to further clarify, My test server is an exact copy of my test server. Database and all

**Comment by Cynist3r** [comment]
I would also like to add, tat as of last night it was working perfectly in my test server after multiple restarts and testing. But now the same error?

**Comment by MaDHouSe79** [comment]
is the script the same script from your test server or did you download just download it? cause i hade add something but that did not work well, so i remove it, so maby you have that one?

**Comment by Cynist3r** [comment]
Yes i drag and dropped the working one from the test server into my main server. Making sure anything i have modified was also moved. It was working fine in my test server. I woke up the next day and i received the error in both the test and the live

**Comment by MaDHouSe79** [comment]
you need to go in the server file at the buttom you see a dataabse MySql execute if you have that at the bottom than you have a the bad one, or you download a new one cause i already fix that issue.
