### ISSUE TITLE
[Enhancement] ParkedViewDistance

### ISSUE THREAD

**Issue by bosskitz** [MaDHouSe79/mh-parking#43]
Great script here, frankly speaking.
Curious though. would there be any chance in the future that the Config.ParkedViewDistance will have an actual function?
Thanks!

**Comment by MaDHouSe79** [comment]
Its already there...

https://github.com/MaDHouSe79/mh-parking/blob/53302235dd374cee0869e89bd6e3bc24042d76f3/client/main.lua#L256

**Comment by MaDHouSe79** [comment]
aa this value was not used, i just add to it ;)
