### ISSUE TITLE
Hello Madhouse can you help me? About fivem mh-parking?

### ISSUE THREAD

**Issue by ENES27BMW** [MaDHouSe79/mh-parking#45]
I am a strict follower of yours. But I need help with something. I downloaded the "mh-parking" and "mh-vehiclekeys" posts you shared. However, when I want to park my car, it gives the error I mentioned in the pictures. And the vehicle spawns locked. But I cannot get into the vehicle at all. When I press the L button, it gives the warning "Vehicle is unlocked" repeatedly. It doesn't say "vehicle locked".
(But actually the vehicle is locked and cannot be unlocked)

I pointed out the errors in the pictures. Would you be helping me in this regard? Thank you from now.
If you can spare your valuable time for me, I would like to pay you your fee within my means. This is very important for me.

Note: I checked all the settings in the config file. I don't think there is anything wrong. Even though I have /park-addvip permission, unfortunately it did not solve my problem.

At the same time, when I open the "Debug console" setting, it gives this error.
![Screenshot_3](https://github.com/MaDHouSe79/mh-parking/assets/154616212/1c7fe5ca-feca-4030-8dd8-686a5829287d)
![Screenshot_4](https://github.com/MaDHouSe79/mh-parking/assets/154616212/e91aa30c-a9f1-46b0-8020-50606a96b56f)
![Screenshot_6](https://github.com/MaDHouSe79/mh-parking/assets/154616212/517b299b-0238-4ea9-8b75-db672feb9d5d)

**Comment by ENES27BMW** [comment]
![Screenshot_3](https://github.com/MaDHouSe79/mh-parking/assets/154616212/3fc8951b-84fb-4847-9835-35b54915da63)
![Screenshot_4](https://github.com/MaDHouSe79/mh-parking/assets/154616212/b0d68389-9d9c-4c24-896f-8072dc7debcc)
![Screenshot_6](https://github.com/MaDHouSe79/mh-parking/assets/154616212/b2464eb0-8703-45fc-a69c-13476f11bed3)

**Comment by MaDHouSe79** [comment]
Hi, those messages in your console are not errors but warnings and that can't hurt, I still have to solve this but I haven't gotten around to it. do you have the vehicles in your shared vehicles.lua?

**Comment by ENES27BMW** [comment]
Yes, there is no problem with the qb-core/shared/vehicles.lua file you mentioned. In order to avoid any problems, "Sentinel, premiere etc." is included in the game. I tried it through the tools named. But the result is the same in all of them. I've been using this script for months. But last week all my server files were deleted. That's why I decided to create a server from scratch. I made all the files using QB-Core original files. But my problem was not resolved in any way. I would be very happy if you could help me solve the problem. I am ready to support you financially as much as I can. This script is very important to me
![Screenshot_7](https://github.com/MaDHouSe79/mh-parking/assets/154616212/8b881a28-8f4e-44ec-89d6-02f82bc49a52)

**Comment by CottonMouthMax** [comment]
was there a fix for this? i am having the same issue
