### ISSUE TITLE
Vehicle Being Removed

### ISSUE THREAD

**Issue by bosskitz** [MaDHouSe79/mh-parking#48]
Hello,

Up to this moment, we are still utilizing this  amazing script.
I didn't activate VIP, literally everyone can park anywhere.
No one's getting any errors related to this script.

There's just one thing I would like to know if possible.
How do I make it so the car, if left unparked won't automatically disappear.
I mean there are instances where a player automatically gets disconnected while driving due to some random issues like intermittent connection or maybe kicked by the anti-cheat. The vehicle would actually disappear. Maybe I can put a Wait(time) before it is removed?

Hope this is possible, thanks...

**Comment by MaDHouSe79** [comment]
Thanks 😄 👍 

If you want to park it you need to press F5 very quick 😄 

But what you want is, when someone disconnected that you autosave the vehicle, cause that's what you basily mean right?
I didn't add that feature, but it's possible with a few adjustments. 

the reason why I didn't add this is, if they happen to fly or jump and they fall out the game, it saves the vehicle in the air and they can't get it, they have to call an admin for help.

**Comment by bosskitz** [comment]
Hello,

Mmmmm I understand this but it's not what I really want I was pertaining to.
Basically, if they accidentally disconnect, I just want the car to be visible and it should not be parked because they did not pressed F5. I just wanted to not make it disappear right away.

What's happening currently is, if they disconnect and no one is around, the car will disappear immediately.
Maybe there's a way to put 5 minutes before it disappears so that when they come back, they can F5 to park it properly.

**Comment by MaDHouSe79** [comment]
> Hello,
> 
> Mmmmm I understand this but it's not what I really want I was pertaining to. Basically, if they accidentally disconnect, I just want the car to be visible and it should not be parked because they did not pressed F5. I just wanted to not make it disappear right away.
> 
> What's happening currently is, if they disconnect and no one is around, the car will disappear immediately. Maybe there's a way to put 5 minutes before it disappears so that when they come back, they can F5 to park it properly.

Thit is what fivem does by it self, like i said if no one is around that player the vehicle auto removed by fivem, my script does not do that, if someone is around than the vehicle should stay, if I'm not mistaken.

**Comment by bosskitz** [comment]
Apologies, for some reason, if I were to use only qb-garages, if player disconnects, the car actually doesn't disappear right away if they accidentally disconnects. But I prefer mh-parking instead of the default garage script.
I am so confused. Player can come back and park the vehicle in garage if using only qb-garages so I thought there's something I can do.

**Comment by bosskitz** [comment]
> Thanks 😄 👍
> 
> If you want to park it you need to press F5 very quick 😄
> 
> But what you want is, when someone disconnected that you autosave the vehicle, cause that's what you mean right? I didn't add that feature, but it's possible with a few adjustments.
> 
> the reason why I didn't add this is, if they happen to fly or jump and they fall out the game, it saves the vehicle in the air and they can't get it, they have to call an admin for help.

Hey, I was just thinking, is there a way to have this added? What adjustments should do I need to do? Thank you so much!
I think, I can deal with this. Auto parking when disconnected.

**Comment by bosskitz** [comment]
I see... I understand. Thanks for your reply though.
Not a big deal, we will continue using mh-parking anyway haha. Thanks man. More power!
