### ISSUE TITLE
When i Park and restart server the car dosent spawn back

### ISSUE THREAD

**Issue by Fresnowolf** [MaDHouSe79/mh-parking#51]

**Comment by Fresnowolf** [comment]
Im still having this issue, when i restart my server all the parked cars are gone. i tried addon and not addon. any fix to this?

**Comment by MaDHouSe79** [comment]
just update the code, try if it now works for you.

**Comment by Crav07** [comment]
Just to clarify, the vehicle is in the database and I receive keys upon logging on, however the car is not spawning. Using /park and /unpark work as intended. But if I log out and log back in the vehicle fails to spawn, the same happens after a restart.

**Comment by MaDHouSe79** [comment]
i just update the code again, try if it now work for you.
